version: 2
sources:
  - name: pagila
    database: pagila
    schema: public
    tables:
      - name: actor
      - name: film
      - name: film_actor
      - name: film_category
      - name: category
      - name: customer
      - name: address
      - name: city
      - name: country
      - name: inventory
      - name: rental
      - name: payment
      - name: staff
      - name: store